os: osx
osx_image: xcode9.2

language: node_js
node_js:
  - "8"
  - "10"

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

git:
  depth: 5

install:
  - |
    security create-keychain -p travis build.keychain
    security default-keychain -s build.keychain
    security unlock-keychain -p travis build.keychain
    echo $CERTIFICATE_OSX_P12 | base64 --decode > certificate.p12
    security import certificate.p12 -k build.keychain -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign
    security set-key-partition-list -S apple-tool:,apple: -s -k travis build.keychain
  - cd packages/graphql-playground-electron
  - yarn install
  - yarn release

notifications:
  email: false

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
