notifications:
  email: false

os:
  #- linux
  - osx

osx_image: xcode9.2

language: node_js
node_js: "8"

install:
  #- security create-keychain -p mysecretpassword build.keychain
  #- security default-keychain -s build.keychain
  #- security unlock-keychain -p mysecretpassword build.keychain
  - echo $CERTIFICATE_OSX_P12 | base64 --decode > certificate.p12
  - security import certificate.p12 -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign
  - npm i -g yarn
  - cd packages/graphql-playground-electron
  - yarn install
  - yarn mac
