version: 2

jobs:

  playground-build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm i -g yarn
      - run: cd packages/graphql-playground && yarn
      - run: cd packages/graphql-playground && yarn build

  electron-build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: |
          security create-keychain -p travis build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p travis build.keychain
          echo $CERTIFICATE_OSX_P12 | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k travis build.keychain
      - run: sudo npm i -g yarn
      # needed for release process
      - run: brew install gettext
      - run: cd packages/graphql-playground-electron && yarn
      - run: cd packages/graphql-playground-electron && yarn release

workflows:
  version: 2
  build:
    jobs:
      - playground-build
      - electron-build
