jobs:

  playground-build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm i -g yarn
      - run: cd packages/graphql-playground && yarn
      - run: cd packages/graphql-playground && yarn build

  electron-build-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: npm i -g yarn
      - run: echo $CERTIFICATE_OSX_P12 | base64 --decode > certificate.p12
      - run: security import certificate.p12 -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign
      - run: cd packages/graphql-playground-electron && yarn
        # - run: cd packages/graphql-playground-electron && yarn release

workflows:
  version: 2
  build:
    jobs:
      - playground-build
      - electron-build-osx
