schemaPath: schema.graphql
extensions:
  endpoints:
    default:
      url: 'https://airbnb.now.sh'
      subscription: 'wss://airbnb.now.sh'
    local:
      url: 'http://localhost:${env:PORT}/graphql'
      subscription: 'ws://localhost:${env:PORT}'

