schemaPath: schema.graphql
extensions:
  endpoints:
    default:
      url: 'https://airbnb.now.sh'
      subscription: 'wss://airbnb.now.sh'
    local:
      url: 'http://localhost:4000/graphql'
      subscription: 'ws://localhost:4000'

