service: playground-test

provider:
  name: aws
  runtime: nodejs6.10


functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: handler.playgroundHandler
    events:
    - http:
        path: /
        method: get
        cors: true

plugins:
  - serverless-offline
